# Point promtail to the loki service
config:
  clients:
    - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
# Resource tuning for homelab
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
# Add a more patient readiness probe to prevent timeouts on startup in a homelab environment
readinessProbe:
  httpGet:
    path: /ready
    port: http-metrics
  initialDelaySeconds: 30
  timeoutSeconds: 5
