apiVersion: v1
kind: Secret
metadata:
  name: monitoring-basic-auth
  namespace: monitoring
type: Opaque
data:
  auth: YWRtaW46JGFwcjEkTi9EUlBEOVgkWEZwNC5HN1dUd3FCUzJFSTNBZGEu # admin:prometheus-admin 
