apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: monitoring-stack-alerts
  namespace: monitoring
  labels:
    app: prometheus-stack
    release: prometheus-stack
spec:
  groups:
    - name: monitoring.rules
      rules:
        - alert: MonitoringStackDown
          expr: up{job=~"prometheus-stack.*"} == 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Monitoring stack component is down"
            description: "{{ $labels.job }} has been down for more than 5 minutes."
        - alert: HighMemoryUsage
          expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.9
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "High memory usage detected"
            description: "Node {{ $labels.instance }} has memory usage above 90% for more than 10 minutes."
        - alert: HighCPUUsage
          expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "High CPU usage detected"
            description: "Node {{ $labels.instance }} has CPU usage above 80% for more than 10 minutes."
        - alert: DiskSpaceLow
          expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) * 100 < 10
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Disk space is running low"
            description: "Filesystem {{ $labels.mountpoint }} on {{ $labels.instance }} has less than 10% space remaining."
        - alert: PodCrashLooping
          expr: rate(kube_pod_container_status_restarts_total[15m]) > 0
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Pod is crash looping"
            description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is restarting frequently."
