apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus-stack
resources:
  - ns.yaml
  - alertmanager-http-route.yaml
  - grafana-http-route.yaml
  - prometheus-http-route.yaml
  - custom-alerts.yaml
  - custom-servicemonitors.yaml
  - network-policies.yaml
# Strategic merge patches to handle resource conflicts
patchesStrategicMerge:
  - alertmanager-config.yaml
helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 75.13.0
    releaseName: kube-prometheus-stack
    namespace: prometheus-stack
    valuesFile: values.yaml
    includeCRDs: true # This is the key setting!
