- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: GOMAXPROCS
    value: "2"
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: GOMEMLIMIT
    value: "3GiB"
