apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blackbox-exporter
  namespace: monitoring
  labels:
    app: blackbox-exporter
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: blackbox-exporter
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: thanos-components
  namespace: monitoring
  labels:
    app: thanos
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: thanos
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: loki-components
  namespace: monitoring
  labels:
    app: loki
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
  endpoints:
    - port: http-metrics
      interval: 30s
      path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tempo-components
  namespace: monitoring
  labels:
    app: tempo
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tempo
  endpoints:
    - port: http-metrics
      interval: 30s
      path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio-components
  namespace: monitoring
  labels:
    app: minio
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: minio
  endpoints:
    - port: http-minio
      interval: 30s
      path: /minio/v2/metrics/cluster
