# VictoriaMetrics Operator
victoria-metrics-operator:
  enabled: true

# VMSingle - single-node VictoriaMetrics
vmsingle:
  enabled: true
  spec:
    retentionPeriod: "7d"
    replicaCount: 1
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi
    # Ensure the service name is predictable
    serviceName: "victoriametrics-vmsingle"

# VMAgent - metrics collection agent
vmagent:
  enabled: true
  spec:
    # Reference the VMSingle service
    remoteWrite:
      - url: "http://victoriametrics-vmsingle:8429/api/v1/write"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

grafana:
  enabled: false

# Kube State Metrics
kube-state-metrics:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

# Node Exporter - optimized for homelab
node-exporter:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

# Disable default alerting rules for homelab
defaultRules:
  create: false
