apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tempo-stack
resources:
  - ns.yaml
  - tempo-http-route.yaml
helmCharts:
  - name: tempo
    repo: https://grafana.github.io/helm-charts
    version: 2.8.0
    releaseName: tempo
    namespace: tempo-stack
    valuesFile: values.yaml
    includeCRDs: true
