apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-state-metrics
rules:
- apiGroups: [ '' ]
  resources:
  - configmaps
  - secrets
  - nodes
  - pods
  - services
  - endpoints
  - resourcequotas
  - replicationcontrollers
  - limitranges
  - persistentvolumeclaims
  - persistentvolumes
  - namespaces
  verbs: [ "list", "watch" ]
- apiGroups: [ "coordination.k8s.io" ]
  resources:
  - leases
  verbs: [ "list", "watch" ]
- apiGroups: [ "apps" ]
  resources:
  - statefulsets
  - daemonsets
  - deployments
  - replicasets
  verbs: [ "list", "watch" ]
- apiGroups: [ "batch" ]
  resources:
  - cronjobs
  - jobs
  verbs: [ "list", "watch" ]
- apiGroups: [ "autoscaling" ]
  resources:
  - horizontalpodautoscalers
  verbs: [ "list", "watch" ]
- apiGroups: [ "policy" ]
  resources:
  - poddisruptionbudgets
  verbs: [ "list", "watch" ]
- apiGroups: [ "networking.k8s.io" ]
  resources:
  - networkpolicies
  - ingresses
  verbs: [ "list", "watch" ]
- apiGroups: [ "storage.k8s.io" ]
  resources:
  - storageclasses
  - volumeattachments
  verbs: [ "list", "watch" ]
- apiGroups: [ "admissionregistration.k8s.io" ]
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs: [ "list", "watch" ]
- apiGroups: [ "certificates.k8s.io" ]
  resources:
  - certificatesigningrequests
  verbs: [ "list", "watch" ]
