apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: enact-cluster
  namespace: default
spec:
  parentRefs:
    - name: gateway-external
      namespace: gateway
#      sectionName: api-tls
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
    - backendRefs:
        - name: kubernetes
          namespace: default
          port: 443
