apiVersion: operator.victoriametrics.com/v1beta1
kind: VLAgent
metadata:
  name: vlagent
  namespace: victoria-metrics
spec:
  config:
    - inputConfig: |
        inputs:
          - name: kubernetes
            type: kubernetes
            kubernetes:
              include_pod_metadata: true
              include_namespace_metadata: true
    - outputConfig: |
        outputs:
          - name: vlogs
            type: victorialogs
            victorialogs:
              url: http://vlogs-victoria-logs.monitoring.svc.cluster.local:9428/insert/jsonline
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
