apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
spec:
  description: Project for monitoring stack components
  sourceRepos:
    - '*'
  destinations:
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: kube-system # Required for promtail and some exporters
      server: https://kubernetes.default.svc
    - namespace: argocd # Required for prometheus-rbac application
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  roles:
    - name: admin
      description: Admin role for monitoring project
      policies:
        - p, proj:monitoring:admin, applications, *, monitoring/*, allow
        - p, proj:monitoring:admin, projects, *, monitoring, allow
        - p, proj:monitoring:admin, repositories, *, *, allow
        - p, proj:monitoring:admin, clusters, *, *, allow
        - p, proj:monitoring:admin, exec, *, */*, allow
      groups:
        - argocd-admins
