persistence:
  enabled: true
  storageClassName: longhorn
  size: 500Mi
  accessModes:
    - ReadWriteOnce
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
config:
  clients:
    - url: http://loki.loki.svc.cluster.local:3100/loki/api/v1/push
