apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana
resources:
  - ns.yaml
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - httproute.yaml
  - secret.yaml
configMapGenerator:
  - name: grafana-datasources
    files:
      - datasource.yaml
  - name: grafana-dashboards-provider
    files:
      - dashboards.yaml
  - name: grafana-dashboards
    files:
      - dashboards/victoriametrics.json
generatorOptions:
  disableNameSuffixHash: true
