apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana
resources:
  - ns.yaml
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - httproute.yaml
  - secret.yaml
  - grafana.yaml
