adminPassword: "prom-operator"

persistence:
  enabled: true
  storageClassName: longhorn
  size: 2Gi
  accessModes:
    - ReadWriteOnce

sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    folder: /var/lib/grafana/dashboards
    searchNamespace: monitoring

# Disable init container to avoid Longhorn formatting issues
initChownData:
  enabled: false

# Add proper security contexts
securityContext:
  runAsNonRoot: true
  runAsUser: 472
  runAsGroup: 472
  fsGroup: 472

containerSecurityContext:
  runAsNonRoot: true
  runAsUser: 472
  runAsGroup: 472
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL

# Use Recreate strategy to avoid mount conflicts
deploymentStrategy:
  type: Recreate

# Add pod annotations for better Longhorn compatibility
podAnnotations:
  cluster-autoscaler.kubernetes.io/safe-to-evict: "true"