# Grafana Helm values for home lab
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
adminPassword: "admin"
# Add more values as needed for your environment
