adminPassword: "prom-operator"
persistence:
  enabled: true
  storageClassName: longhorn
  size: 2Gi
  accessModes:
    - ReadWriteOnce
  # Add explicit volume binding mode to prevent stuck volumes
  volumeBindingMode: Immediate
  # Add proper reclaim policy
  reclaimPolicy: Retain
sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    folder: /var/lib/grafana/dashboards
    searchNamespace: monitoring
# Disable init container to avoid Longhorn formatting issues
initChownData:
  enabled: false
# Use security context to handle permissions
securityContext:
  runAsUser: 472
  runAsGroup: 472
  fsGroup: 472
# Add proper container security context
containerSecurityContext:
  runAsUser: 472
  runAsGroup: 472
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL
