apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: victoriametrics
  namespace: victoriametrics-operator
  labels:
    app: victoriametrics
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  parentRefs:
    - name: external-gateway
      namespace: gateway-system
  hostnames:
    - "metrics.vanillax.xyz"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: victoriametrics
          port: 8428
          kind: Service
