apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: victoria-metrics
resources:
  - vmsingle.yaml
  - vmagent.yaml
  - vmalertmanager.yaml
  - vmalert.yaml
  - vmauth.yaml
  - vmuser.yaml
helmCharts:
  - name: victoria-metrics-operator
    repo: https://victoriametrics.github.io/helm-charts/
    version: 0.51.4 # update as needed
    releaseName: victoria-metrics-operator
    namespace: victoria-metrics
    includeCRDs: true
