apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: victoria-metrics
resources:
  # Core VictoriaMetrics CRs
  - core/vmsingle.yaml
  - core/vmagent.yaml
  - core/vmalert.yaml
  - core/vmauth.yaml
  - core/vmuser.yaml
  - core/vmrule.yaml
  # Scrape configs
  - scrapes/kubelet-scrape.yaml
  - scrapes/apiserver-scrape.yaml
  - scrapes/coredns-scrape.yaml
  - scrapes/kube-controller-manager-scrape.yaml
  - scrapes/kube-scheduler-scrape.yaml
  - scrapes/longhorn-scrape.yaml
  - scrapes/cilium-scrape.yaml
  - scrapes/node-exporter-scrape.yaml
  - scrapes/kube-state-metrics-scrape.yaml
  - scrapes/cert-manager-scrape.yaml
  - scrapes/vmsingle-scrape.yaml
  - scrapes/etcd-scrape.yaml
  # HTTPRoute
  - httproute.yaml
helmCharts:
  - name: victoria-metrics-operator
    repo: https://victoriametrics.github.io/helm-charts/
    version: 0.51.4 # update as needed
    releaseName: victoria-metrics-operator
    namespace: victoria-metrics
    includeCRDs: true
    valuesFile: operator/values.yaml
