apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: victoria-metrics
resources:
  - vmsingle.yaml
  - vmagent.yaml
  - vmalert.yaml
  - vmauth.yaml
  - vmuser.yaml
  - httproute.yaml
  - kubelet-scrape.yaml
  - apiserver-scrape.yaml
  - coredns-scrape.yaml
  - kube-controller-manager-scrape.yaml
  - kube-scheduler-scrape.yaml
  - longhorn-scrape.yaml
  - cilium-scrape.yaml
  - node-exporter-scrape.yaml
  - kube-state-metrics-scrape.yaml
  - cert-manager-scrape.yaml
  - vmsingle-scrape.yaml
helmCharts:
  - name: victoria-metrics-operator
    repo: https://victoriametrics.github.io/helm-charts/
    version: 0.51.4 # update as needed
    releaseName: victoria-metrics-operator
    namespace: victoria-metrics
    includeCRDs: true
