# VictoriaMetrics Operator values
# Based on https://docs.victoriametrics.com/helm/victoriametrics-operator/

# Enable admission webhooks for validation
admissionWebhooks:
  enabled: true
  certManager:
    enabled: true
# Service account configuration
serviceAccount:
  create: true
  automountServiceAccountToken: true
# Operator configuration
image:
  repository: victoriametrics/victoria-metrics-operator
  tag: v0.37.0
  pullPolicy: IfNotPresent
# Resource limits
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
# Service configuration
service:
  type: ClusterIP
  servicePort: 8080
  webhookPort: 9443
# Pod configuration
podAnnotations: {}
podLabels: {}
# Security context
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000
# Node selector
nodeSelector: {}
# Tolerations
tolerations: []
# Affinity
affinity: {}
# Topology spread constraints
topologySpreadConstraints: []
# Termination grace period
terminationGracePeriodSeconds: 30
# Watch namespaces (empty means watch all namespaces)
watchNamespaces: []
# Service monitor for self-monitoring
serviceMonitor:
  enabled: true
  vm: true
  interval: "30s"
  scrapeTimeout: "10s"
  annotations: {}
  extraLabels: {}
