apiVersion: v1
kind: ConfigMap
metadata:
  name: vmalert-rules
  namespace: victoriametrics-operator
  labels:
    app: vmalert
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  # Basic alert rules for VictoriaMetrics
  victoriametrics-rules.yaml: "groups:\n  - name: victoriametrics\n    rules:\n      - alert: VictoriaMetricsDown\n        expr: up{job=\"victoriametrics\"} == 0\n        for: 1m\n        labels:\n          severity: critical\n        annotations:\n          summary: \"VictoriaMetrics instance is down\"\n          description: \"VictoriaMetrics instance has been down for more than 1 minute\"\n      \n      - alert: VictoriaMetricsHighMemoryUsage\n        expr: process_resident_memory_bytes{job=\"victoriametrics\"} > 1.5e9\n        for: 5m\n        labels:\n          severity: warning\n        annotations:\n          summary: \"VictoriaMetrics high memory usage\"\n          description: \"VictoriaMetrics is using more than 1.5GB of memory\"\n      \n      - alert: VictoriaMetricsHighCPUUsage\n        expr: rate(process_cpu_seconds_total{job=\"victoriametrics\"}[5m]) > 0.8\n        for: 5m\n        labels:\n          severity: warning\n        annotations:\n          summary: \"VictoriaMetrics high CPU usage\"\n          description: \"VictoriaMetrics CPU usage is above 80%\" "
