apiVersion: operator.victoriametrics.com/v1beta1
kind: VMScrape
metadata:
  name: victoriametrics
  namespace: victoriametrics-operator
  labels:
    app: victoriametrics
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: victoriametrics
  endpoints:
    - port: http
      interval: 30s
      scrapeTimeout: 10s
      path: /metrics
