apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: victoriametrics
  namespace: victoriametrics-operator
  labels:
    app: victoriametrics
spec:
  endpoints:
    - port: http
      interval: 30s
      scrapeTimeout: 10s
      path: /metrics
  jobLabel: app
  selector:
    matchLabels:
      app: victoriametrics
