apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: vmsingle
  namespace: victoria-metrics
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vmsingle
  endpoints:
    - port: 8428
      interval: 30s
      path: /metrics
