apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: victoriametrics
  namespace: victoriametrics-operator
  labels:
    app: victoriametrics
spec:
  # Single binary mode configuration
  retentionPeriod: "30d"
  # Storage configuration
  storage:
    # Use Longhorn for persistent storage
    storageClassName: longhorn
    accessMode: ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  # Service configuration
  service:
    type: ClusterIP
    port: 8428
  # Pod configuration
  podMetadata:
    labels:
      app: victoriametrics
    annotations: {}
  # Container configuration
  containers:
    - name: victoriametrics
      image: victoriametrics/victoria-metrics:v1.96.0
      imagePullPolicy: IfNotPresent
      args:
        - --httpListenAddr=:8428
        - --storageDataPath=/storage
        - --retentionPeriod=30d
        - --maxHourlySeries=1000000
        - --maxDailySeries=1000000
        - --search.maxUniqueTimeseries=1000000
      ports:
        - name: http
          containerPort: 8428
          protocol: TCP
      resources:
        limits:
          cpu: 1000m
          memory: 2Gi
        requests:
          cpu: 500m
          memory: 1Gi
      volumeMounts:
        - name: storage
          mountPath: /storage
  # Volumes
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: victoriametrics-storage
  # Security context
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 1000
  # Node selector
  nodeSelector: {}
  # Tolerations
  tolerations: []
  # Affinity
  affinity: {}
  # Topology spread constraints
  topologySpreadConstraints: []
  # Termination grace period
  terminationGracePeriodSeconds: 30
