apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: loki
helmCharts:
  - name: loki
    repo: https://grafana.github.io/helm-charts
    version: 6.33.0
    releaseName: loki
    namespace: loki
    valuesFile: values.yaml
    includeCRDs: true
resources:
  - httproute.yaml
