apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: loki
namespace: monitoring
helmCharts:
  - name: loki
    repo: https://grafana.github.io/helm-charts
    version: "6.30.1"
    releaseName: loki
    namespace: monitoring
    valuesFile: values-reduced.yaml
resources:
  - http-routes.yaml
  - networkpolicy.yaml
