loki:
  persistence:
    enabled: true
    storageClassName: longhorn
    size: 2Gi
    accessModes:
      - ReadWriteOnce
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
