# Official Loki Single Binary configuration based on Grafana docs
# https://grafana.com/docs/loki/latest/setup/install/helm/install-monolithic/

deploymentMode: SingleBinary
singleBinary:
  replicas: 1
  persistence:
    enabled: true
    storageClass: longhorn
    size: 2Gi
    accessModes:
      - ReadWriteOnce
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
loki:
  # Required: replication_factor must be 1 for single replica
  commonConfig:
    replication_factor: 1
  # Modern schema configuration (required)
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  # Pattern ingester configuration
  pattern_ingester:
    enabled: false
  # Basic limits and retention
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
    retention_period: 168h # 7 days
  # Storage configuration for filesystem
  storage_config:
    filesystem:
      directory: /var/loki/chunks
  # Required storage configuration for Helm chart templates
  storage:
    type: filesystem
    bucketNames:
      chunks: "chunks"
      ruler: "ruler"
      admin: "admin"
# Disable all distributed mode components (required)
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0
# Disable minio (using filesystem storage)
minio:
  enabled: false
# Optional: Enable ruler for alerting
ruler:
  enabled: false
