apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
helmCharts:
  - name: prometheus-blackbox-exporter
    repo: https://prometheus-community.github.io/helm-charts
    version: 9.0.1
    releaseName: blackbox-exporter
    namespace: monitoring
    valuesFile: values.yaml
