image:
  registry: docker.io
  repository: prom/blackbox-exporter
  tag: v0.24.0
  pullPolicy: IfNotPresent
resources:
  requests:
    memory: 64Mi
    cpu: 50m
  limits:
    memory: 128Mi
    cpu: 100m
securityContext:
  runAsNonRoot: true
  runAsUser: 65534
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
config:
  modules:
    http_2xx:
      prober: http
      timeout: 5s
      http:
        valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
        valid_status_codes: [] # Defaults to 2xx
        method: GET
        headers:
          Host: vhost.example.com
          Accept-Language: en-US
        no_follow_redirects: false
        fail_if_ssl: false
        fail_if_not_ssl: false
        fail_if_body_matches_regexp: []
        fail_if_body_not_matches_regexp: []
        fail_if_header_matches: []
        fail_if_header_not_matches: []
        tls_config:
          insecure_skip_verify: false
        preferred_ip_protocol: "ip4"
        ip_protocol_fallback: true
    http_post_2xx:
      prober: http
      timeout: 5s
      http:
        method: POST
        headers:
          Content-Type: application/json
        body: '{}'
    tcp_connect:
      prober: tcp
      timeout: 5s
    pop3s_banner:
      prober: tcp
      tcp:
        query_response:
          - expect: "^+OK"
        tls: true
        tls_config:
          insecure_skip_verify: false
    grpc:
      prober: grpc
      grpc:
        tls: true
        preferred_ip_protocol: "ip4"
    grpc_plain:
      prober: grpc
      grpc:
        tls: false
        service: "service1"
    ssh_banner:
      prober: tcp
      timeout: 5s
      tcp:
        query_response:
          - expect: "^SSH-2.0-"
          - send: "SSH-2.0-blackbox-ssh-check"
    irc_banner:
      prober: tcp
      timeout: 5s
      tcp:
        query_response:
          - send: "NICK prober"
          - send: "USER prober prober prober :prober"
          - expect: "PING :([^ ]+)"
            send: "PONG ${1}"
          - expect: "^:[^ ]+ 001"
    icmp:
      prober: icmp
      timeout: 5s
      icmp:
        preferred_ip_protocol: "ip4"
        source_ip_address: ""
    dns_soa:
      prober: dns
      timeout: 5s
      dns:
        query_name: "kubernetes.default.svc.cluster.local"
        query_type: "SOA"
    dns_a:
      prober: dns
      timeout: 5s
      dns:
        query_name: "kubernetes.default.svc.cluster.local"
        query_type: "A"
serviceMonitor:
  enabled: true
  defaults:
    labels:
      release: prometheus-stack
    interval: 30s
    scrapeTimeout: 30s
  targets:
    - name: prometheus-stack-grafana
      url: http://prometheus-stack-grafana.monitoring.svc.cluster.local
      module: http_2xx
    - name: prometheus-stack-kube-prom-prometheus
      url: http://prometheus-stack-kube-prom-prometheus.monitoring.svc.cluster.local:9090
      module: http_2xx
    - name: prometheus-stack-kube-prom-alertmanager
      url: http://prometheus-stack-kube-prom-alertmanager.monitoring.svc.cluster.local:9093
      module: http_2xx
    - name: thanos-query
      url: http://thanos-query.monitoring.svc.cluster.local:9090
      module: http_2xx
    - name: loki-gateway
      url: http://loki-gateway.monitoring.svc.cluster.local
      module: http_2xx
    - name: tempo-query-frontend
      url: http://tempo-query-frontend.monitoring.svc.cluster.local:3100
      module: http_2xx
    - name: minio-console
      url: http://minio-minio.monitoring.svc.cluster.local:9001
      module: http_2xx
    - name: kubernetes-api
      url: https://kubernetes.default.svc:443
      module: http_2xx
prometheusRule:
  enabled: true
  additionalLabels:
    release: prometheus-stack
  rules:
    - alert: BlackboxProbeFailed
      expr: probe_success == 0
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: Blackbox probe failed (instance {{ $labels.instance }})
        description: "Probe failed\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    - alert: BlackboxSlowProbe
      expr: avg_over_time(probe_duration_seconds[1m]) > 1
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: Blackbox slow probe (instance {{ $labels.instance }})
        description: "Blackbox probe took more than 1s to complete\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    - alert: BlackboxProbeHttpFailure
      expr: probe_http_status_code <= 199 OR probe_http_status_code >= 400
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: Blackbox probe HTTP failure (instance {{ $labels.instance }})
        description: "HTTP status code is not 200-399\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    - alert: BlackboxSslCertificateWillExpireSoon
      expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 30
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: Blackbox SSL certificate will expire soon (instance {{ $labels.instance }})
        description: "SSL certificate expires in 30 days\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    - alert: BlackboxSslCertificateWillExpireSoon
      expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 3
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: Blackbox SSL certificate will expire soon (instance {{ $labels.instance }})
        description: "SSL certificate expires in 3 days\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    - alert: BlackboxProbeSlowHttp
      expr: avg_over_time(probe_http_duration_seconds[1m]) > 1
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: Blackbox probe slow HTTP (instance {{ $labels.instance }})
        description: "HTTP request took more than 1s\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    - alert: BlackboxProbeSlowPing
      expr: avg_over_time(probe_icmp_duration_seconds[1m]) > 1
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: Blackbox probe slow ping (instance {{ $labels.instance }})
        description: "Blackbox ping took more than 1s\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
networkPolicy:
  enabled: false # We'll create custom ones
podSecurityPolicy:
  enabled: false
strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
  type: RollingUpdate
dnsPolicy: ClusterFirst
restartPolicy: Always
hostNetwork: false
podDisruptionBudget:
  maxUnavailable: 1
