replicaCount: 1

image:
  repository: ghcr.io/headlamp-k8s/headlamp
  tag: v0.29.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    memory: 128Mi
    cpu: "100m"
  limits:
    memory: 256Mi
    cpu: "500m" 