# Example Probe for the Kubernetes API Server
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: kubernetes-apiserver
  labels:
    probe: kubernetes-apiserver
spec:
  jobName: kubernetes-apiservers
  interval: 60s
  module: http_2xx
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:9115
    scheme: https
  targets:
    staticConfig:
      static:
        - https://kubernetes.default.svc
