# Resource tuning for homelab
resources:
  requests:
    cpu: 20m
    memory: 32Mi
  limits:
    cpu: 50m
    memory: 64Mi
# Enable the ServiceMonitor for Prometheus to scrape this exporter
serviceMonitor:
  enabled: true
# Default configuration for blackbox exporter
# We will define Probes separately as CRDs
config:
  modules:
    http_2xx:
      prober: http
      timeout: 5s
      http:
        valid_http_versions:
          - HTTP/1.1
          - HTTP/2.0
        valid_status_codes: [] # Any 2xx status code is considered valid
        method: GET
        no_follow_redirects: false
        preferred_ip_protocol: "ip4"
