apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: monitoring
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.7.2
    helm:
      releaseName: loki
      values: "loki:\n  replicas: 1\n  # Use filesystem persistence, suitable for a single-node setup\n  persistence:\n    enabled: true\n    size: 10Gi\n    storageClassName: openebs-hostpath # IMPORTANT: Match your StorageClass\n\n  # Resource tuning for homelab\n  resources:\n    requests:\n      cpu: 200m\n      memory: 300Mi\n    limits:\n      cpu: 1000m\n      memory: 1Gi\n  \n  # Use a simple, single-binary deployment mode\n  commonConfig:\n    replication_factor: 1\n  \n  storage:\n    type: 'filesystem'\n\n# Disable other components in the chart, we will manage them separately\ngrafana:\n  enabled: false\nprometheus:\n  enabled: false\npromtail:\n  enabled: false\ngateway:\n  enabled: false\n"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
