apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - project.yaml
  - prometheus-stack/
  - loki-stack/
  - promtail/
  - tempo/
  - minio/
  - thanos/
  - blackbox-exporter/
  - dashboards/
