apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-components
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/mitch-ross/k3s-argocd-starter.git # Change this to your repo
        revision: HEAD
        directories:
          - path: monitoring/argocd/applications/*
  template:
    metadata:
      name: '{{ .path.basename }}'
      labels:
        type: monitoring
    spec:
      project: monitoring
      source:
        # Use Kustomize to render the Helm charts and resources
        repoURL: https://github.com/mitch-ross/k3s-argocd-starter.git # Change this to your repo
        targetRevision: HEAD
        path: '{{ .path.path }}'
      destination:
        server: https://kubernetes.default.svc
        # All monitoring components go into the 'monitoring' namespace
        namespace: 'monitoring'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=false # The namespace is created separately
          - ServerSideApply=true
