apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
# NOTE: The matrix generator is used here to allow explicit mapping of each monitoring component's path to its correct destination namespace.
# This is required because kube-state-metrics and node-exporter must be deployed to kube-system and monitoring namespaces, not their folder names.
# Without this, Argo CD would deploy to a namespace matching the folder name, which would break metrics collection and ServiceScrape selectors.
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - path: monitoring/victoria-metrics
                  namespace: victoria-metrics
                - path: monitoring/grafana
                  namespace: grafana
                - path: monitoring/victorialogs
                  namespace: victorialogs
                - path: monitoring/kube-state-metrics
                  namespace: kube-system
                - path: monitoring/node-exporter
                  namespace: monitoring
          - git:
              repoURL: https://github.com/mitchross/k3s-argocd-starter.git
              revision: HEAD
              directories:
                - path: monitoring/victoria-metrics
                - path: monitoring/grafana
                - path: monitoring/victorialogs
                - path: monitoring/kube-state-metrics
                - path: monitoring/node-exporter
  template:
    metadata:
      name: 'monitoring-{{path.basename}}'
      labels:
        type: monitoring
    spec:
      project: monitoring
      source:
        plugin:
          name: kustomize-build-with-helm
        repoURL: https://github.com/mitchross/k3s-argocd-starter.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
      ignoreDifferences:
        - group: ""
          kind: Secret
          name: victoria-metrics-operator-validation
          namespace: victoria-metrics
          jsonPointers:
            - /data
        - group: admissionregistration.k8s.io
          kind: ValidatingWebhookConfiguration
          name: victoria-metrics-operator-admission
          jqPathExpressions:
            - '.webhooks[]?.clientConfig.caBundle'
