apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  # NOTE: We use a list generator here (instead of a git generator) to allow explicit mapping of each monitoring component's path to its correct destination namespace and application name.
  # This is required because some components (like kube-state-metrics) must be deployed to special namespaces (e.g., kube-system), not just their folder name.
  # This approach prevents accidental misplacement of critical monitoring components and ensures clarity and maintainability.
  generators:
  - list:
      elements:
      - path: monitoring/victoria-metrics
        namespace: victoria-metrics
        name: victoria-metrics
      - path: monitoring/grafana
        namespace: grafana
        name: grafana
      - path: monitoring/victorialogs
        namespace: victorialogs
        name: victorialogs
        # Includes Vector log shipper and eventrouter for Kubernetes event logging
      - path: monitoring/kube-state-metrics
        namespace: kube-system
        name: kube-state-metrics
      - path: monitoring/node-exporter
        namespace: monitoring
        name: node-exporter
  template:
    metadata:
      name: 'monitoring-{{name}}'
      labels:
        type: monitoring
    spec:
      project: monitoring
      source:
        plugin:
          name: kustomize-build-with-helm
        repoURL: https://github.com/mitchross/k3s-argocd-starter.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
        - RespectIgnoreDifferences=true
      ignoreDifferences:
      - group: ""
        kind: Secret
        name: victoria-metrics-operator-validation
        namespace: victoria-metrics
        jsonPointers:
        - /data
      - group: admissionregistration.k8s.io
        kind: ValidatingWebhookConfiguration
        name: victoria-metrics-operator-admission
        jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'
