apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - httproutes.yaml
helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 55.11.0
    releaseName: kube-prometheus-stack
    namespace: monitoring
    valuesFile: values.yaml
    includeCRDs: true
commonLabels:
  app.kubernetes.io/name: kube-prometheus-stack
