longhorn:
  replicas: 1
csi:
  attacher:
    replicas: 1
  provisioner:
    replicas: 1
  resizer:
    replicas: 1
  snapshotter:
    replicas: 1
defaultSettings:
  defaultDataPath: "/var/lib/longhorn"
preUpgradeChecker:
  jobEnabled: false
persistence:
  defaultClass: true
  defaultClassReplicaCount: 2
  defaultFsType: ext4
  reclaimPolicy: Retain
ingress:
  enabled: false
