# Reduced Tempo configuration for resource-constrained environments
global:
  image:
    registry: docker.io
storage:
  trace:
    backend: s3
    s3:
      bucket: tempo
      endpoint: minio.monitoring.svc.cluster.local:9000
      access_key: minioadmin
      secret_key: minioadmin
      insecure: true
config: |
  multitenancy_enabled: false
  usage_report:
    reporting_enabled: false
  compactor:
    compaction:
      block_retention: 24h # Reduced to 1 day
  distributor:
    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:4318
          grpc:
            endpoint: 0.0.0.0:4317
  ingester:
    lifecycler:
      ring:
        kvstore:
          store: memberlist
        replication_factor: 1  # Reduced from 2
  memberlist:
    join_members:
      - tempo-distributed-memberlist
  querier:
    max_concurrent_queries: 5  # Reduced from 20
  server:
    http_listen_port: 3100
    log_level: info
  storage:
    trace:
      backend: s3
      local:
        path: /var/tempo/traces
      wal:
        path: /var/tempo/wal
traces:
  otlp:
    http:
      enabled: true
    grpc:
      enabled: true
serviceMonitor:
  enabled: true
  labels:
    release: prometheus-stack
# Minimal deployment
ingester:
  replicas: 1 # Reduced from 3
  resources:
    requests:
      cpu: 100m # Reduced from 500m
      memory: 256Mi # Reduced from 1Gi
    limits:
      cpu: 200m # Reduced from 1000m
      memory: 512Mi # Reduced from 2Gi
  persistence:
    enabled: true
    size: 5Gi # Reduced from 10Gi
    storageClass: longhorn
distributor:
  replicas: 1 # Reduced from 3
  resources:
    requests:
      cpu: 50m # Reduced from 250m
      memory: 128Mi # Reduced from 512Mi
    limits:
      cpu: 100m # Reduced from 500m
      memory: 256Mi # Reduced from 1Gi
queryFrontend:
  replicas: 1 # Reduced from 2
  resources:
    requests:
      cpu: 50m # Reduced from 250m
      memory: 128Mi # Reduced from 512Mi
    limits:
      cpu: 100m # Reduced from 500m
      memory: 256Mi # Reduced from 1Gi
querier:
  replicas: 1 # Reduced from 3
  resources:
    requests:
      cpu: 100m # Reduced from 500m
      memory: 256Mi # Reduced from 1Gi
    limits:
      cpu: 200m # Reduced from 1000m
      memory: 512Mi # Reduced from 2Gi
compactor:
  replicas: 1
  resources:
    requests:
      cpu: 50m # Reduced from 250m
      memory: 128Mi # Reduced from 512Mi
    limits:
      cpu: 100m # Reduced from 500m
      memory: 256Mi # Reduced from 1Gi
  persistence:
    enabled: true
    size: 2Gi # Reduced from 5Gi
    storageClass: longhorn
gateway:
  enabled: true
  replicas: 1 # Reduced from 2
  resources:
    requests:
      cpu: 25m # Reduced from 100m
      memory: 64Mi # Reduced from 128Mi
    limits:
      cpu: 50m # Reduced from 200m
      memory: 128Mi # Reduced from 256Mi
memcached:
  enabled: false
enterprise:
  enabled: false
