# Tempo Configuration for Distributed Tracing
tempo:
  # Storage configuration
  storage:
    trace:
      backend: s3
      s3:
        bucket: tempo-traces
        endpoint: minio.monitoring.svc.cluster.local:9000
        access_key: minioadmin
        secret_key: minioadmin
        insecure: true
  # Retention configuration
  retention: 72h
  # Global overrides
  global_overrides:
    max_traces_per_user: 20000
    max_bytes_per_trace: 5000000
  # Distributor configuration
  distributor:
    receivers:
      jaeger:
        protocols:
          thrift_http:
            endpoint: 0.0.0.0:14268
          grpc:
            endpoint: 0.0.0.0:14250
          thrift_binary:
            endpoint: 0.0.0.0:6832
          thrift_compact:
            endpoint: 0.0.0.0:6831
      zipkin:
        endpoint: 0.0.0.0:9411
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      opencensus:
        endpoint: 0.0.0.0:55678
  # Ingester configuration
  ingester:
    max_block_duration: 5m
  # Compactor configuration  
  compactor:
    compaction:
      block_retention: 72h
  # Querier configuration
  querier:
    max_concurrent_queries: 20
  # Query frontend configuration
  query_frontend:
    max_outstanding_per_tenant: 100
# Resource management
resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1000m
    memory: 2Gi
# Persistence for traces
persistence:
  enabled: true
  storageClassName: longhorn
  size: 30Gi
# Service monitor for Prometheus integration
serviceMonitor:
  enabled: true
  labels:
    release: kube-prometheus-stack
# Gateway configuration for external access
gateway:
  enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
