apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: thanos
namespace: monitoring
helmCharts:
  - name: thanos
    repo: https://charts.bitnami.com/bitnami
    version: "13.2.1"
    releaseName: thanos
    namespace: monitoring
    valuesFile: values.yaml
resources:
  - objstore-config.yaml
  - http-routes.yaml
  - networkpolicy.yaml
