apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: monitoring
type: Opaque
stringData:
  objstore.yml: "type: S3\nconfig:\n  bucket: thanos\n  endpoint: minio.monitoring.svc.cluster.local:9000\n  access_key: minioadmin\n  secret_key: minioadmin\n  insecure: true\n  signature_version2: false\n  put_user_metadata: {}\n  http_config:\n    idle_conn_timeout: 90s\n    response_header_timeout: 2m\n    insecure_skip_verify: true\n  trace:\n    enable: false "
