# Reduced Thanos configuration for resource-constrained environments
global:
  storageClass: longhorn
  imageRegistry: docker.io
existingObjstoreSecret: thanos-objstore-config
existingObjstoreSecretItems:
  - key: objstore.yml
    path: objstore.yml
query:
  enabled: true
  replicaCount: 1
  dnsDiscovery:
    enabled: true
    sidecarsService: thanos-sidecar
    sidecarsNamespace: monitoring
  stores:
    - thanos-store-gateway:10901
  resources:
    requests:
      memory: 128Mi # Reduced from 256Mi
      cpu: 50m # Reduced from 125m
    limits:
      memory: 256Mi # Reduced from 512Mi
      cpu: 100m # Reduced from 250m
  securityContext:
    enabled: true
    runAsNonRoot: true
    runAsUser: 1001
    fsGroup: 1001
  service:
    ports:
      http: 9090
      grpc: 10901
queryFrontend:
  enabled: false
storegateway:
  enabled: true
  replicaCount: 1
  persistence:
    enabled: true
    storageClass: longhorn
    size: 10Gi # Reduced from 20Gi
  resources:
    requests:
      memory: 256Mi # Reduced from 512Mi
      cpu: 100m # Reduced from 250m
    limits:
      memory: 512Mi # Reduced from 1Gi
      cpu: 200m # Reduced from 500m
  securityContext:
    enabled: true
    runAsNonRoot: true
    runAsUser: 1001
    fsGroup: 1001
  config: |-
    type: FILESYSTEM
    config:
      directory: /data
compactor:
  enabled: true
  persistence:
    enabled: true
    storageClass: longhorn
    size: 20Gi # Reduced from 50Gi
  resources:
    requests:
      memory: 256Mi # Reduced from 1Gi
      cpu: 100m # Reduced from 500m
    limits:
      memory: 512Mi # Reduced from 2Gi
      cpu: 200m # Reduced from 1000m
  securityContext:
    enabled: true
    runAsNonRoot: true
    runAsUser: 1001
    fsGroup: 1001
  retentionResolutionRaw: 3d # Reduced from 7d
  retentionResolution5m: 14d # Reduced from 30d
  retentionResolution1h: 30d # Reduced from 90d
  config: |-
    type: FILESYSTEM
    config:
      directory: /data
ruler:
  enabled: false
bucketweb:
  enabled: false
sidecar:
  enabled: false # Deployed with Prometheus stack
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    labels:
      release: prometheus-stack
