# Thanos Configuration for Long-term Metrics Storage
# Based on actual Bitnami Thanos chart documentation

# Global configuration
global:
  storageClass: longhorn
# Object storage configuration - inline YAML format
objstoreConfig: |-
  type: S3
  config:
    bucket: thanos
    endpoint: minio.monitoring.svc.cluster.local:9000
    access_key: minioadmin
    secret_key: minioadmin
    insecure: true
    signature_version2: false
# Query component - provides unified querying interface
query:
  enabled: true
  replicaCount: 2
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m
  stores:
    - "thanos-storegateway:10901"
    - "kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:10901"
  extraFlags:
    - "--log.level=info"
    - "--query.replica-label=prometheus_replica"
    - "--query.auto-downsampling"
# Query Frontend - provides caching and query splitting
queryFrontend:
  enabled: true
  replicaCount: 1
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 250m
  config: |-
    type: IN-MEMORY
    config:
      max_size: 512MB
      max_size_items: 1000
      validity: 6h
# Store Gateway - provides access to historical data
storegateway:
  enabled: true
  replicaCount: 1
  resources:
    requests:
      memory: 1Gi
      cpu: 500m
    limits:
      memory: 2Gi
      cpu: 1000m
  persistence:
    enabled: true
    storageClass: longhorn
    size: 50Gi
  extraFlags:
    - "--log.level=info"
    - "--store.grpc.series-sample-limit=300000"
    - "--store.grpc.series-max-concurrency=20"
# Compactor - compacts and downsamples metrics
compactor:
  enabled: true
  resources:
    requests:
      memory: 1Gi
      cpu: 500m
    limits:
      memory: 2Gi
      cpu: 1000m
  persistence:
    enabled: true
    storageClass: longhorn
    size: 100Gi
  # Retention and downsampling configuration
  retentionResolutionRaw: 30d
  retentionResolution5m: 120d
  retentionResolution1h: 1y
  extraFlags:
    - "--log.level=info"
    - "--compact.cleanup-interval=5m"
    - "--compact.consistency-delay=30m"
    - "--delete-delay=48h"
# Ruler - disabled for simplicity
ruler:
  enabled: false
# Bucket Web - web interface for object storage
bucketweb:
  enabled: true
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 200m
# Metrics configuration
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    labels:
      release: kube-prometheus-stack
