apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: etcd
  namespace: victoria-metrics
  labels:
    release: victoria-metrics
spec:
  selector:
    matchLabels:
      component: etcd
  namespaceSelector:
    matchNames:
      - kube-system
  endpoints:
    - port: etcd-metrics
      interval: 30s
      scheme: https
      tlsConfig:
        caFile: /etc/etcd/pki/ca.crt
        certFile: /etc/etcd/pki/etcd-client.crt
        keyFile: /etc/etcd/pki/etcd-client.key
        insecureSkipVerify: true
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: node
