apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: kubelet
  namespace: victoria-metrics
spec:
  selector:
    matchLabels:
      k8s-app: kubelet
  endpoints:
    - port: http-metrics
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      interval: 30s
      path: /metrics
