apiVersion: v1
kind: ServiceAccount
metadata:
  name: eventrouter
  namespace: victorialogs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eventrouter
rules:
- apiGroups: [ "" ]
  resources: [ "events" ]
  verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eventrouter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eventrouter
subjects:
- kind: ServiceAccount
  name: eventrouter
  namespace: victorialogs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventrouter
  namespace: victorialogs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventrouter
  template:
    metadata:
      labels:
        app: eventrouter
    spec:
      serviceAccountName: eventrouter
      containers:
      - name: eventrouter
        image: ghcr.io/opsgenie/kubernetes-eventrouter:v0.4
        env:
        - name: ROUTER_OUTPUT
          value: "stdout"
        resources:
          limits:
            cpu: 50m
            memory: 64Mi
          requests:
            cpu: 10m
            memory: 32Mi
