apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vector
  namespace: victorialogs
  labels:
    app: vector
spec:
  selector:
    matchLabels:
      app: vector
  template:
    metadata:
      labels:
        app: vector
    spec:
      serviceAccountName: default
      containers:
      - name: vector
        image: timberio/vector:0.36.0-alpine
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: vector-config
          mountPath: /etc/vector/
        env:
        - name: VECTOR_CONFIG
          value: /etc/vector/vector.yaml
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: vector-config
        configMap:
          name: vector-config
