apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
spec:
  description: Core infrastructure components
  sourceRepos:
    - https://github.com/mitchross/k3s-argocd-starter.git
  destinations:
    - namespace: kube-system
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: ClusterRole
    - group: ""
      kind: ClusterRoleBinding
    - group: "rbac.authorization.k8s.io"
      kind: Role
    - group: "rbac.authorization.k8s.io"
      kind: RoleBinding
    - group: "gateway.networking.k8s.io"
      kind: HTTPRoute
    - group: "apiextensions.k8s.io"
      kind: CustomResourceDefinition
    - group: "batch"
      kind: Job
    - group: ""
      kind: Namespace
    - group: ""
      kind: ServiceAccount
    - group: "apps"
      kind: StatefulSet
    - group: "apps"
      kind: Deployment
  namespaceResourceWhitelist:
    - group: ""
      kind: Deployment
    - group: ""
      kind: Service
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
    - group: "rbac.authorization.k8s.io"
      kind: Role
    - group: "rbac.authorization.k8s.io"
      kind: RoleBinding
    - group: ""
      kind: ServiceAccount
  roles:
    - name: admin
      description: Admin role for infrastructure project
      policies:
        - p, proj:infrastructure:admin, applications, *, infrastructure/*, allow
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: applications
  namespace: argocd
spec:
  description: User applications
  sourceRepos:
    - https://github.com/mitchross/k3s-argocd-starter.git
  destinations:
    - namespace: app-*
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: cert-manager.io
      kind: ClusterIssuer
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
    - group: ""
      kind: Service
    - group: ""
      kind: Deployment
    - group: ""
      kind: Pod
    - group: ""
      kind: ServiceAccount
    - group: ""
      kind: PersistentVolumeClaim
    - group: "networking.k8s.io"
      kind: Ingress
    - group: "batch"
      kind: Job
    - group: "batch"
      kind: CronJob
    - group: "rbac.authorization.k8s.io"
      kind: Role
    - group: "rbac.authorization.k8s.io"
      kind: RoleBinding
  roles:
    - name: admin
      description: Admin role for applications project
      policies:
        - p, proj:applications:admin, applications, *, applications/*, allow
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
spec:
  description: Monitoring and observability components
  sourceRepos:
    - https://github.com/mitchross/k3s-argocd-starter.git
  destinations:
    - namespace: kube-system
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "monitoring.coreos.com"
      kind: ServiceMonitor
    - group: "monitoring.coreos.com"
      kind: PodMonitor
    - group: ""
      kind: ServiceAccount
  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
    - group: ""
      kind: Service
    - group: ""
      kind: Deployment
    - group: ""
      kind: ServiceAccount
  roles:
    - name: admin
      description: Admin role for monitoring project
      policies:
        - p, proj:monitoring:admin, applications, *, monitoring/*, allow
