# Minimal Prometheus values for home lab
prometheus:
  enabled: true
  prometheusSpec:
    retention: 7d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: [ReadWriteOnce]
          resources:
            requests:
              storage: 5Gi
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi
    securityContext:
      runAsNonRoot: true
      runAsUser: 65534
      fsGroup: 65534
    scrapeInterval: 60s
    evaluationInterval: 60s
    scrapeTimeout: 15s
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    additionalScrapeConfigs: []
    remoteWrite: []
    alerting:
      alertmanagers:
        - namespace: monitoring
          name: prometheus-alertmanager
          port: 9093
alertmanager:
  enabled: true
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: [ReadWriteOnce]
          resources:
            requests:
              storage: 2Gi
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    securityContext:
      runAsNonRoot: true
      runAsUser: 65534
      fsGroup: 65534
    retention: 72h
grafana:
  enabled: false
nodeExporter:
  enabled: true
kubeStateMetrics:
  enabled: true
prometheusOperator:
  enabled: true
