#
# Common settings for the stack
#
global:
  # This should be overridden with your actual domain
  # e.g., via a config management tool or manually
  domain: yourdomain.xyz
#
# Prometheus Configuration
#
prometheus:
  prometheusSpec:
    replicas: 1
    # Adjust retention and storage size for homelab use
    retention: 15d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: openebs-hostpath # IMPORTANT: Match your StorageClass
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
    # Resource limits tuned for a small cluster
    resources:
      requests:
        cpu: 250m
        memory: 750Mi
      limits:
        cpu: 1
        memory: 1.5Gi
    # Scrape configs for other components will be added via ServiceMonitors
#
# Alertmanager Configuration
#
alertmanager:
  enabled: true
  alertmanagerSpec:
    replicas: 1
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: openebs-hostpath # IMPORTANT: Match your StorageClass
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 200m
        memory: 250Mi
  ingress:
    enabled: true
    ingressClassName: cilium # IMPORTANT: Match your IngressClass
    annotations:
      cert-manager.io/cluster-issuer: cloudflare-cluster-issuer
    hosts:
      - "alertmanager.{{ .Values.global.domain }}"
    paths:
      - /
    tls:
      - secretName: alertmanager-tls
        hosts:
          - "alertmanager.{{ .Values.global.domain }}"
#
# Grafana Configuration
#
grafana:
  enabled: true
  replicas: 1
  adminPassword: "prom-operator" # CHANGE THIS default password
  persistence:
    enabled: true
    type: pvc
    storageClassName: openebs-hostpath # IMPORTANT: Match your StorageClass
    accessModes: ["ReadWriteOnce"]
    size: 2Gi
  resources:
    requests:
      cpu: 100m
      memory: 150Mi
    limits:
      cpu: 300m
      memory: 300Mi
  # Pre-configure Loki datasource
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki.monitoring.svc.cluster.local:3100 # Updated service name
      jsonData:
        maxLines: 1000
  # Pre-load dashboards from the community
  # These are sourced from grafana.com/grafana/dashboards/
  dashboardProviders:
    grafana-com-dashboards:
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: 'file'
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      # Node Exporter Full Dashboard
      node-exporter:
        gnetId: 1860
        revision: 36
        datasource: Prometheus
      # Kubernetes Cluster Overview
      k8s-cluster:
        gnetId: 3119
        revision: 24
        datasource: Prometheus
      # Cilium Dashboard
      cilium:
        gnetId: 10922
        revision: 23
        datasource: Prometheus
  ingress:
    enabled: true
    ingressClassName: cilium # IMPORTANT: Match your IngressClass
    annotations:
      cert-manager.io/cluster-issuer: cloudflare-cluster-issuer
    hosts:
      - "grafana.{{ .Values.global.domain }}"
    paths:
      - /
    tls:
      - secretName: grafana-tls
        hosts:
          - "grafana.{{ .Values.global.domain }}"
#
# Resource tuning for exporters
#
prometheus-node-exporter:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
kube-state-metrics:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
