apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: vmalert
  namespace: victoria-metrics
spec:
  datasource:
    url: "http://vmsingle-vmsingle.victoria-metrics.svc:8429"
  notifiers:
    - url: "http://vmalertmanager.victoria-metrics.svc:9093"
  evaluationInterval: "10s"
  selectAllByDefault: true
