apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vmsingle-pvc
  namespace: victoria-metrics
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn
