apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - minio-route.yaml
helmCharts:
  - name: minio
    repo: https://charts.min.io/
    version: "5.4.0"
    releaseName: minio
    namespace: monitoring
    valuesFile: values.yaml
    includeCRDs: false
