# MinIO Configuration for Observability Storage Backend
mode: standalone
# Authentication
rootUser: minioadmin
rootPassword: minioadmin
# Resource management
resources:
  requests:
    memory: 500Mi
    cpu: 250m
  limits:
    memory: 1Gi
    cpu: 500m
# Persistence configuration
persistence:
  enabled: true
  storageClass: longhorn
  accessMode: ReadWriteOnce
  size: 100Gi
# Service configuration
service:
  type: ClusterIP
  port: 9000
# Console service
consoleService:
  type: ClusterIP
  port: 9001
# Environment variables
environment:
  MINIO_PROMETHEUS_AUTH_TYPE: "public"
  MINIO_UPDATE: "off"
  MINIO_BROWSER_REDIRECT_URL: "https://minio-console.vanillax.xyz"
# Default buckets to create
buckets:
  - name: thanos
    policy: none
    purge: false
  - name: loki-data
    policy: none
    purge: false
  - name: loki-ruler
    policy: none
    purge: false
  - name: loki-admin
    policy: none
    purge: false
  - name: tempo-traces
    policy: none
    purge: false
# Security context
securityContext:
  enabled: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
# Metrics configuration
metrics:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: kube-prometheus-stack
    namespace: monitoring
# Disable ingress (using Gateway API)
ingress:
  enabled: false
consoleIngress:
  enabled: false
# Additional labels
additionalLabels:
  app.kubernetes.io/part-of: observability-stack
