apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: promtail-stack
resources:
  - ns.yaml
helmCharts:
  - name: promtail
    repo: https://grafana.github.io/helm-charts
    version: 7.1.0
    releaseName: promtail
    namespace: promtail-stack
    valuesFile: values.yaml
    includeCRDs: true
