apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
helmCharts:
  - name: k8s-monitoring
    repo: https://grafana.github.io/helm-charts
    version: 2.0.16
    releaseName: k8s-monitoring
    namespace: monitoring
    valuesFile: values.yaml
    includeCRDs: true
commonLabels:
  app.kubernetes.io/name: k8s-monitoring
