# https://github.com/grafana/helm-charts/blob/main/charts/loki/values.yaml
loki:
  persistence:
    enabled: true
    storageClass: longhorn
    size: 10Gi
  config:
    chunk_store_config:
      max_look_back_period: 0s
    table_manager:
      retention_deletes_enabled: true
      retention_period: 30d
