# https://github.com/grafana/helm-charts/blob/main/charts/loki/values.yaml
deploymentMode: SingleBinary
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: "filesystem"
    filesystem:
      chunks_directory: "/data/loki/chunks"
      rules_directory: "/data/loki/rules"
  chunk_store_config:
    max_look_back_period: 0s
  table_manager:
    retention_deletes_enabled: true
    retention_period: 30d
  ruler:
    enabled: true
    storage:
      type: "local"
      local:
        directory: "/data/loki/rules"
    ring:
      kvstore:
        store: "inmemory"
    rule_path: "/tmp/loki/rules"
    alertmanager_url: ""
    # external_url:
    # enable_api: true
    # enable_alertmanager_v2: true
persistence:
  enabled: true
  storageClass: longhorn
  size: 20Gi
singleBinary:
  replicas: 1
  tolerations:
    - operator: Exists
monitoring:
  dashboards:
    enabled: true
  rules:
    enabled: true
  serviceMonitor:
    enabled: false
  selfMonitoring:
    enabled: false
    lokiCanary:
      enabled: false
test:
  enabled: false
