# https://github.com/grafana/helm-charts/blob/main/charts/tempo/values.yaml
tempo:
  persistence:
    enabled: true
    storageClass: longhorn
    size: 10Gi
  searchEnabled: true
  tolerations:
    - operator: Exists
  metricsGenerator:
    enabled: true
    remoteWriteUrl: http://prometheus-server.k8s-monitoring.svc.cluster.local/api/v1/write
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 2Gi
metrics:
  serviceMonitor:
    enabled: false
test:
  enabled: false
