# https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
persistence:
  enabled: true
  storageClass: longhorn
  size: 10Gi
adminPassword: prom-operator
ingress:
  enabled: false
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        uid: loki
        url: http://loki-gateway.k8s-monitoring.svc.cluster.local
        isDefault: false
        jsonData:
          derivedFields:
            - datasourceUid: tempo
              matcherRegex: "trace_id=([a-fA-F0-9]{32})"
              name: trace_id
              url: "$${__value.raw}"
      - name: Prometheus
        type: prometheus
        uid: prometheus
        url: http://prometheus-server.k8s-monitoring.svc.cluster.local
        isDefault: true
      - name: Tempo
        type: tempo
        uid: tempo
        url: http://tempo.k8s-monitoring.svc.cluster.local:3200
        isDefault: false
        jsonData:
          httpMethod: "POST"
          tracesToLogs:
            datasourceUid: "loki"
            tags: ["job", "instance", "pod", "namespace"]
            mappedTags: [{key: "service.name", value: "job"}]
            spanStartTimeShift: "1h"
            spanEndTimeShift: "1h"
            filterByTraceID: true
            filterBySpanID: false
sidecar:
  dashboards:
    enabled: true
    searchNamespace: "k8s-monitoring"
    provider:
      name: sidecar-provider
      orgid: 1
      folder: "General"
      type: file
      disableDelete: false
      allowUiUpdates: true
      updateIntervalSeconds: 30
      options:
        path: /var/lib/grafana/dashboards/default
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: "default"
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
dashboards:
  default:
    node-exporter:
      gnetId: 1860
      revision: 37
      datasource: Prometheus
    kubernetes-all-in-one-cluster:
      gnetId: 16099
      revision: 11
      datasource: Prometheus
    kubernetes-all-in-one-cluster-en:
      gnetId: 15757
      revision: 6
      datasource: Prometheus
    kubernetes-cluster-monitoring:
      gnetId: 10856
      revision: 11
      datasource: Prometheus
    kubernetes-deployment:
      gnetId: 14282
      revision: 4
      datasource: Prometheus
    loki-log:
      gnetId: 7336
      revision: 1
      datasource: Loki
    loki:
      gnetId: 13277
      revision: 1
      datasource: Loki
