cluster:
  name: k3s-nuc
clusterMetrics:
  enabled: true
logs:
  enabled: true
grafana:
  enabled: true
  persistence:
    enabled: true
    storageClass: longhorn
    size: 10Gi
  ingress:
    enabled: false
  datasources:
    - name: Prometheus
      type: prometheus
      uid: prometheus
      url: http://k8s-monitoring-prometheus.k8s-monitoring.svc.cluster.local:9090
      isDefault: true
      jsonData:
        httpMethod: "POST"
        timeInterval: "30s"
    - name: Loki
      type: loki
      uid: loki
      url: http://k8s-monitoring-loki.k8s-monitoring.svc.cluster.local:3100
      isDefault: false
      jsonData:
        derivedFields:
          - datasourceUid: tempo
            matcherRegex: "trace_id=([a-fA-F0-9]{32})"
            name: trace_id
            url: "$${__value.raw}"
    - name: Tempo
      type: tempo
      uid: tempo
      url: http://k8s-monitoring-tempo.k8s-monitoring.svc.cluster.local:3100
      isDefault: false
      jsonData:
        httpMethod: "POST"
        tracesToLogs:
          datasourceUid: "loki"
          tags: ["job", "instance", "pod", "namespace"]
          mappedTags: [{key: "service.name", value: "job"}]
          spanStartTimeShift: "1h"
          spanEndTimeShift: "1h"
          filterByTraceID: true
          filterBySpanID: false
  dashboards:
    default:
      node-exporter:
        url: https://grafana.com/api/dashboards/1860/revisions/37/download
      kubernetes-all-in-one-cluster:
        url: https://grafana.com/api/dashboards/16099/revisions/11/download
      kubernetes-all-in-one-cluster-en:
        url: https://grafana.com/api/dashboards/15757/revisions/6/download
      kubernetes-cluster-monitoring:
        url: https://grafana.com/api/dashboards/10856/revisions/11/download
      kubernetes-deployment:
        url: https://grafana.com/api/dashboards/14282/revisions/4/download
      loki-log:
        url: https://grafana.com/api/dashboards/7336/revisions/1/download
      loki:
        url: https://grafana.com/api/dashboards/13277/revisions/1/download
prometheus:
  enabled: true
  persistence:
    enabled: true
    storageClass: longhorn
    size: 20Gi
  alertmanager:
    enabled: true
    ingress:
      enabled: false
    config:
      global:
        resolve_timeout: 5m
      route:
        group_by: ['job']
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 12h
        receiver: 'null'
      receivers:
        - name: 'null'
loki:
  persistence:
    enabled: true
    storageClass: longhorn
    size: 10Gi
tempo:
  enabled: true
